trigger:
- master

pool:
  name: Default

steps:

- checkout: self


- script: mvn clean test
  displayName: Build and Run Selenium Tests


- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Automation Test Results'


- task: PublishBuildArtifacts@1
  displayName: Publish Test Reports
  inputs:
    pathToPublish: 'target/surefire-reports'
    artifactName: 'TestReports'


    